# ── DNS 拦截 & 遥测域名屏蔽 ─────────────────────────────────────

# 需要拦截的遥测域名
TELEMETRY_DOMAINS=(
    "statsig.anthropic.com"
    "sentry.io"
    "o1137031.ingest.sentry.io"
    "cdn.growthbook.io"
)

# 写入 HOSTALIASES 文件（备用层：gethostbyname 级别拦截）
# HOSTALIASES 格式为 hostname-to-hostname 映射（非 IP）
_write_blocked_hosts() {
    local hosts_file="$CAC_DIR/blocked_hosts"
    {
        echo "# cac — blocked telemetry domains"
        echo "# Generated by cac setup, used via HOSTALIASES"
        for domain in "${TELEMETRY_DOMAINS[@]}"; do
            printf '%s\tlocalhost\n' "$domain"
        done
    } > "$hosts_file"
}

# 写入 Node.js DNS guard 模块（核心层：dns.lookup / dns.resolve 级别拦截 + mTLS）
_write_dns_guard_js() {
    local guard_file="$CAC_DIR/cac-dns-guard.js"
    cat > "$guard_file" << 'DNSGUARD_EOF'
// ═══════════════════════════════════════════════════════════════
// cac-dns-guard.js
// NS 层级遥测域名拦截 ｜ mTLS 证书注入 ｜ fetch 防泄露
// 通过 NODE_OPTIONS="--require <this>" 注入到 Claude Code 进程
// ═══════════════════════════════════════════════════════════════
'use strict';

var dns  = require('dns');
var net  = require('net');
var tls  = require('tls');
var http = require('http');
var https = require('https');
var fs   = require('fs');

// ─── 1. NS 层级遥测域名拦截 ──────────────────────────────────

var BLOCKED_DOMAINS = new Set([
    'statsig.anthropic.com',
    'sentry.io',
    'o1137031.ingest.sentry.io',
    'cdn.growthbook.io',
]);

/**
 * 检查域名是否在拦截名单中（含子域匹配）
 * e.g. "foo.sentry.io" 会匹配 "sentry.io"
 */
function isDomainBlocked(hostname) {
    if (!hostname) return false;
    var h = hostname.toLowerCase().replace(/\.$/,'');
    if (BLOCKED_DOMAINS.has(h)) return true;
    var parts = h.split('.');
    for (var i = 1; i < parts.length - 1; i++) {
        if (BLOCKED_DOMAINS.has(parts.slice(i).join('.'))) return true;
    }
    return false;
}

function makeBlockedError(hostname, syscall) {
    var msg = 'connect ECONNREFUSED (blocked by cac): ' + hostname;
    var err = new Error(msg);
    err.code     = 'ECONNREFUSED';
    err.errno    = -111;
    err.hostname = hostname;
    err.syscall  = syscall || 'connect';
    return err;
}

// ── 1a. 拦截 dns.lookup ──
var _origLookup = dns.lookup;
dns.lookup = function cacLookup(hostname, options, callback) {
    if (typeof options === 'function') { callback = options; options = {}; }
    if (isDomainBlocked(hostname)) {
        var err = makeBlockedError(hostname, 'getaddrinfo');
        if (typeof callback === 'function') process.nextTick(function() { callback(err); });
        return {};
    }
    return _origLookup.call(dns, hostname, options, callback);
};

// ── 1b. 拦截 dns.resolve / resolve4 / resolve6 ──
['resolve','resolve4','resolve6'].forEach(function(method) {
    var orig = dns[method];
    if (!orig) return;
    dns[method] = function(hostname) {
        var args = Array.prototype.slice.call(arguments);
        var cb = args[args.length - 1];
        if (isDomainBlocked(hostname)) {
            var err = makeBlockedError(hostname, 'query');
            if (typeof cb === 'function') process.nextTick(function() { cb(err); });
            return;
        }
        return orig.apply(dns, args);
    };
});

// ── 1c. 拦截 dns.promises ──
if (dns.promises) {
    var _origPLookup = dns.promises.lookup;
    if (_origPLookup) {
        dns.promises.lookup = function cacPromiseLookup(hostname, options) {
            if (isDomainBlocked(hostname)) return Promise.reject(makeBlockedError(hostname, 'getaddrinfo'));
            return _origPLookup.call(dns.promises, hostname, options);
        };
    }
    ['resolve','resolve4','resolve6'].forEach(function(method) {
        var orig = dns.promises[method];
        if (!orig) return;
        dns.promises[method] = function(hostname) {
            if (isDomainBlocked(hostname)) return Promise.reject(makeBlockedError(hostname, 'query'));
            return orig.apply(dns.promises, arguments);
        };
    });
}

// ── 1d. 网络层安全网：拦截 net.connect 到遥测域名 ──
var _origNetConnect    = net.connect;
var _origNetCreateConn = net.createConnection;

function getHostFromArgs(args) {
    if (typeof args[0] === 'object') return args[0].host || args[0].hostname || '';
    return '';
}

function makeBlockedSocket(host) {
    var sock = new net.Socket();
    var err = makeBlockedError(host, 'connect');
    process.nextTick(function() { sock.destroy(err); });
    return sock;
}

net.connect = function cacNetConnect() {
    var host = getHostFromArgs(arguments);
    if (isDomainBlocked(host)) return makeBlockedSocket(host);
    return _origNetConnect.apply(net, arguments);
};
net.createConnection = function cacNetCreateConnection() {
    var host = getHostFromArgs(arguments);
    if (isDomainBlocked(host)) return makeBlockedSocket(host);
    return _origNetCreateConn.apply(net, arguments);
};


// ─── 2. mTLS 客户端证书注入 ──────────────────────────────────

var mtlsCert = process.env.CAC_MTLS_CERT;
var mtlsKey  = process.env.CAC_MTLS_KEY;
var mtlsCa   = process.env.CAC_MTLS_CA;
var proxyHostPort = process.env.CAC_PROXY_HOST || '';

if (mtlsCert && mtlsKey) {
    var certData, keyData, caData;
    try {
        certData = fs.readFileSync(mtlsCert);
        keyData  = fs.readFileSync(mtlsKey);
        if (mtlsCa) caData = fs.readFileSync(mtlsCa);
    } catch(e) {
        certData = null; keyData = null;
    }

    if (certData && keyData) {
        // 仅对代理服务器连接注入 mTLS 证书
        var proxyHost = proxyHostPort.split(':')[0];
        var proxyPort = parseInt(proxyHostPort.split(':')[1], 10) || 0;

        // 2a. 拦截 tls.connect，在代理连接时注入客户端证书
        var _origTlsConnect = tls.connect;
        tls.connect = function cacTlsConnect() {
            // 规范化参数：tls.connect(options[, cb]) 或 tls.connect(port[, host][, options][, cb])
            var args = Array.prototype.slice.call(arguments);
            var options, callback;

            if (typeof args[0] === 'object') {
                options = args[0];
                callback = (typeof args[1] === 'function') ? args[1] : undefined;
            } else {
                // tls.connect(port, host, options, cb) 形式
                var port = args[0];
                var host = (typeof args[1] === 'string') ? args[1] : 'localhost';
                var optIdx = (typeof args[1] === 'string') ? 2 : 1;
                options = (typeof args[optIdx] === 'object') ? args[optIdx] : {};
                options.port = port;
                options.host = host;
                callback = args[args.length - 1];
                if (typeof callback !== 'function') callback = undefined;
            }

            // 仅在连接代理时注入（精确匹配 host:port）
            var targetHost = options.host || options.hostname || '';
            var targetPort = options.port || 0;
            if (proxyHost && targetHost === proxyHost &&
                (proxyPort === 0 || targetPort === proxyPort)) {
                if (!options.cert) {
                    options.cert = certData;
                    options.key  = keyData;
                    if (caData) {
                        options.ca = options.ca
                            ? [].concat(options.ca, caData)
                            : [caData];
                    }
                }
            }

            if (callback) return _origTlsConnect.call(tls, options, callback);
            return _origTlsConnect.call(tls, options);
        };

        // 2b. 注入 CA 到 https.globalAgent（仅信任 CA，不注入客户端私钥）
        if (caData && https.globalAgent && https.globalAgent.options) {
            https.globalAgent.options.ca = https.globalAgent.options.ca
                ? [].concat(https.globalAgent.options.ca, caData)
                : [caData];
        }
    }
}


// ─── 3. fetch 遥测拦截补丁 ──────────────────────────────────
// Node.js 原生 fetch (undici) 不经过 dns.lookup，会绕过 DNS 拦截
// 策略：优先用 node-fetch（走 http/https 模块 → dns.lookup）
//       否则 wrap 原生 fetch 拦截遥测域名

(function patchFetch() {
    if (typeof globalThis === 'undefined') return;

    // 优先加载 node-fetch（基于 http/https 模块，天然走 dns.lookup 拦截链）
    try {
        var nodeFetch = require('node-fetch');
        if (nodeFetch && typeof nodeFetch === 'function') {
            globalThis.fetch = nodeFetch;
            if (nodeFetch.Headers)  globalThis.Headers  = nodeFetch.Headers;
            if (nodeFetch.Request)  globalThis.Request  = nodeFetch.Request;
            if (nodeFetch.Response) globalThis.Response = nodeFetch.Response;
            return;
        }
    } catch(e) {
        // node-fetch 不可用
    }

    // 兜底：包装原生 fetch，至少确保遥测域名被拦截
    if (typeof globalThis.fetch === 'function') {
        var _origFetch = globalThis.fetch;
        globalThis.fetch = function cacFetch(input, init) {
            var hostname;
            try {
                var urlStr = typeof input === 'string' ? input :
                             (input && input.url) ? input.url : '';
                if (urlStr) hostname = new URL(urlStr).hostname;
            } catch(e) { /* ignore */ }

            if (hostname && isDomainBlocked(hostname)) {
                return Promise.reject(makeBlockedError(hostname, 'fetch'));
            }
            return _origFetch(input, init);
        };
    }
})();


// ─── 4. 健康检查 bypass（进程内拦截，精确到 URL）────────────────
// Claude Code 启动时 ping https://api.anthropic.com/api/hello
// Cloudflare 拦截 Node.js TLS 指纹（JA3/JA4）→ 403
// 方案：在 Node.js 层拦截该请求，直接返回 200，不发出任何网络流量
// 仅拦截 health check，不影响 OAuth/API 等其他请求

function isHealthCheck(url) {
    if (!url) return false;
    // 匹配 https://api.anthropic.com/api/hello 或带查询参数的变体
    return /^https?:\/\/api\.anthropic\.com\/api\/hello/.test(url);
}

function makeHealthResponse(callback) {
    var EventEmitter = require('events');
    var body = '{"message":"hello"}';

    // Fake IncomingMessage
    var res = new EventEmitter();
    res.statusCode = 200;
    res.headers = { 'content-type': 'application/json' };
    res.setEncoding = function() { return res; };

    // Callback first (so caller attaches handlers), then emit data/end
    if (typeof callback === 'function') {
        process.nextTick(function() {
            callback(res);
            process.nextTick(function() {
                res.emit('data', body);
                res.emit('end');
            });
        });
    } else {
        process.nextTick(function() {
            res.emit('data', body);
            res.emit('end');
        });
    }

    // Fake ClientRequest (no-op)
    var req = new EventEmitter();
    req.end = function() { return req; };
    req.write = function() { return true; };
    req.destroy = function() {};
    req.setTimeout = function() { return req; };
    req.on = function(ev, fn) { EventEmitter.prototype.on.call(req, ev, fn); return req; };
    return req;
}

// 4a. 拦截 https.get / https.request
var _origHttpsRequest = https.request;
var _origHttpsGet = https.get;

https.request = function cacHttpsRequest(urlOrOpts, optsOrCb, cb) {
    var url = '';
    if (typeof urlOrOpts === 'string') {
        url = urlOrOpts;
    } else if (urlOrOpts && typeof urlOrOpts === 'object' && urlOrOpts.href) {
        url = urlOrOpts.href;
    } else if (urlOrOpts && typeof urlOrOpts === 'object') {
        var proto = urlOrOpts.protocol || 'https:';
        var host = urlOrOpts.hostname || urlOrOpts.host || '';
        var path = urlOrOpts.path || '/';
        url = proto + '//' + host + path;
    }
    var callback = typeof optsOrCb === 'function' ? optsOrCb : cb;
    if (isHealthCheck(url)) return makeHealthResponse(callback);
    return _origHttpsRequest.apply(https, arguments);
};

https.get = function cacHttpsGet(urlOrOpts, optsOrCb, cb) {
    var url = '';
    if (typeof urlOrOpts === 'string') {
        url = urlOrOpts;
    } else if (urlOrOpts && typeof urlOrOpts === 'object' && urlOrOpts.href) {
        url = urlOrOpts.href;
    } else if (urlOrOpts && typeof urlOrOpts === 'object') {
        var proto = urlOrOpts.protocol || 'https:';
        var host = urlOrOpts.hostname || urlOrOpts.host || '';
        var path = urlOrOpts.path || '/';
        url = proto + '//' + host + path;
    }
    var callback = typeof optsOrCb === 'function' ? optsOrCb : cb;
    if (isHealthCheck(url)) return makeHealthResponse(callback);
    return _origHttpsGet.apply(https, arguments);
};

// 4b. 拦截 fetch（undici 不走 https 模块）
(function patchHealthFetch() {
    if (typeof globalThis === 'undefined' || typeof globalThis.fetch !== 'function') return;
    var _prevFetch = globalThis.fetch;
    globalThis.fetch = function cacHealthFetch(input, init) {
        var url = '';
        try {
            url = typeof input === 'string' ? input : (input && input.url) ? input.url : '';
        } catch(e) {}
        if (isHealthCheck(url)) {
            return Promise.resolve(new Response('{"message":"hello"}', {
                status: 200,
                headers: { 'content-type': 'application/json' }
            }));
        }
        return _prevFetch(input, init);
    };
})();
DNSGUARD_EOF
    chmod 644 "$guard_file"
}

# 验证 DNS 拦截是否生效
_check_dns_block() {
    local domain="${1:-statsig.anthropic.com}"
    local guard_file="$CAC_DIR/cac-dns-guard.js"

    if [[ ! -f "$guard_file" ]]; then
        echo "$(_red "✗") DNS guard 模块不存在"
        return 1
    fi

    local result
    result=$(node -e '
        require(process.argv[1]);
        var dns = require("dns");
        dns.lookup(process.argv[2], function(err) {
            process.stdout.write(err && (err.code === "ECONNREFUSED" || err.code === "ENOTFOUND") ? "BLOCKED" : "OPEN");
        });
    ' "$guard_file" "$domain" 2>/dev/null || echo "ERROR")

    if [[ "$result" == "BLOCKED" ]]; then
        echo "$(_green "✓") $domain 已拦截"
        return 0
    else
        echo "$(_red "✗") $domain 未被拦截 ($result)"
        return 1
    fi
}
